wandb:
  entity: null
#  run_id: askkz9i2
  resume: 'auto'

experiment:
    project: "demo"
    name: "intent_prediction"
    output_dir: "/root/autodl-tmp/Show-o/output"

model:
    vq_model:
        type: "magvitv2"
        vq_model_name: "showlab/magvitv2"

    showo:
        pretrained_model_path: "/root/autodl-tmp/hub/models--showlab--show-o-512x512/snapshots/423a38d831052b2b336e80af323eba02267cce38"
        w_clip_vit: False
        vocab_size: 58498
        llm_vocab_size: 50295
        llm_model_path: '/root/autodl-tmp/hub/models--microsoft--phi-1_5/snapshots/675aa382d814580b22651a30acb1a585d7c25963'
        codebook_size: 8192
        num_vq_tokens: 256
        num_new_special_tokens: 10  # <|soi|> <|eoi|> <|sov|> <|eov|> <|t2i|> <|mmu|> <|t2v|> <|v2v|> <|lvg|> <|pad|>

    gradient_checkpointing: True

dataset:
    gen_type: "t2i"
    und_type: "captioning"
    params:
        batch_size: ${training.batch_size}
        shuffle_buffer_size: 1000
        num_workers: 32
        resolution: 256
        pin_memory: True
        persistent_workers: True
    # <SOC> 新增：intent_dataset_path 配置项
    intent_dataset_path: "/root/autodl-tmp/Show-o" # 你的意图数据集的路径
    # <EOC> 新增 intent_dataset_path 配置项结束

    preprocessing:
        max_seq_length: 128
        resolution: 256
        center_crop: False
        random_flip: False

training:
    gradient_accumulation_steps: 1
    cond_dropout_prob: 0.1
    batch_size: 20
    # <SOC> 新增：batch_size_intent 配置项
    batch_size_intent: 8 # 你可以根据你的 GPU 显存大小调整这个值
    # <EOC> 新增 batch_size_intent 配置项结束
    # <SOC> 新增：intent_coeff 配置项
    intent_coeff: 0.5 # intent_flow 的 loss 的权重系数，你可以根据需要调整这个值
    # <EOC> 新增 intent_coeff 配置项结束
